# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import numpy as np

N = 4e6
i = 1
fibonacci = [1]
while i < N:
    fibonacci.append(i)
    i = np.sum(fibonacci[-2:])

even = [i for i in fibonacci if i % 2 == 0]
print(np.sum(even))
